### PR TITLE
cover page and yellow box changes

### PR DESCRIPTION
**Pull request by Hetal2425**
cover page and yellow box changes.

### CODE REVIEW

**Comment by cbleek** [comment]
there is a conflict in CrossLayout.vue. Resolving is not a big issue.

but if you're using Cookies this way, it will only work in spa (Single Page App) mode. If you run the app in ssr (Server Side Renderung) mode by starting with "yarn dev:ssr" you'll get an error

Bildschirmfoto 2019-12-07 um 14 13 45

.

**Comment by cbleek** [comment]
@Hetal2425 can you merge our pull request and push your master please?

**Comment by Hetal2425** [comment]
@cbleek : Yes Sure.

**Comment by Hetal2425** [comment]
@cbleek : Merged code.

**Comment by cbleek** [comment]
Now please modify the code, so it runs in SSR mod too.

move the Notification from https://github.com/cross-solution/cross-solution.de/blob/master/src/layouts/CrossLayout.vue into the https://github.com/cross-solution/cross-solution.de/blob/master/src/boot/gdpr.js

Use LocalStorage instead of Cookies. Like I've done in the gdpr Notification.

The Issue with the splash page in SSR Mode may be solved using the nossr feature of quasar.

https://quasar.dev/vue-components/no-ssr#Usage

Just try it.

**Comment by cbleek** [comment]
and since "gdpr.js" not only contains gdpr.js related code, please rename it to "notifications.js"

**Comment by Hetal2425** [comment]
@cbleek : But I can manage the cookies with respective code of SSR.

Like : this.$q.cookies.get('cookie_name').

Is it okay?

**Comment by Hetal2425** [comment]
I have solved the issue with the cookie syntax of SSR.

Can I push the code?

**Comment by cbleek** [comment]
you can alway push. It's your repo. Ich you push to your master, the commit will appear in the PR.

**Comment by Hetal2425** [comment]
@cbleek : Please check my last committed code.I have used the cookies,but you need to change with Local storage then I will do that.

**Comment by Hetal2425** [comment]
@cbleek : There is the status of "Review requested" .May I need to do something for that or you review the code and merge?

**Comment by Hetal2425** [comment]
@TiSiE : Thanks.

I will take care for next time in commit messages.

**Comment by development0261** [comment]
Hi @cbleek & @TiSiE Good Morning Guys,
I hope you are doing well.

Would you please let me know about new tasks?

Thanks.

**Comment by cbleek** [comment]
TiSiE hat created https://github.com/cross-solution/cross-solution.de/issues/26

**Comment by development0261** [comment]
Great. Thanks.
I will check it.

**Pull request merged**
